name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build MySQL Docker Image
        run: |
          docker build -t my_db -f Dockerfile_mysql .
          docker tag my_db:latest 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_db:latest

      - name: Build App Docker Image
        run: |
          docker build -t my_app -f Dockerfile .
          docker tag my_app:latest 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_app:latest

      - name: Push Docker Images to ECR
        run: |
          docker push 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_db:latest
          docker push 011926502057.dkr.ecr.us-east-1.amazonaws.com/vipinecr/my_app:latest
